---
title: ESS 330 Project Proposals
authors:
  - name: Ava Zelenz
    affiliation: CSU
    roles: writing
    corresponding: true
  - name : Avery Eastman
    affiliation: CSU
    roles: writing
    corresponding: false
    
bibliography: references.bib
---

## Section 1 Ava

#### Title: Monarch Butterfly Decline in the U.S.

Justification: 
  The loss of biodiversity is something that we are seeing more and more of as climate change worsens. This topic is one that I have experience observing back home in New York. Throughout the past 20 or so years, there has been a heavy decrease in the amount of monarch sightings across the country, with an estimated 81% decline in monarchs from 1999 to 2010 [@pleasants2013milkweed]. Monarch population decline is linked to the decline of milkweed population, as they feed primarily on this. Long-term plant surveys have been utilized to evaluate the correlation of milkweed and monarchs, which found a 68% loss of milkweed available to monarchs [@zaya2017long]. This is a significant problem because monarchs are on track to become endangered and extinct, and if the statistics and data show this a main contributor for the decline of milkweed, we can change that and hopefully bring back the population of monarchs and avoid a loss of species and more biodiversity.

Research objective/question/hypothesis: 
  Decline in milkweed growth leads to the decline of monarch populations in the U.S. 
  
  Proposed Methods: The variables I would like to measure are monarch population, milkweed growth within the U.S., and a time span of 20 years. I will perform a statistic test to determine their correlation based on the data that I find. I will also plot the results I get. I will look at the data.gov and on Nature Scientific Data, to find datasets that show the monarch and milkweed correlation. I will also look at DataCite for more data. This scope will be within the U.S. Before I start with my correlation tests, I will assess normality and skewness in the data, and make adjustments to clean the data if necessary. 
  
  Expected Outcomes: I would expect to find that there is a statistically significant value that shows a positive correlation between milkweed and monarch population.
  
## Section 2 

#### Title: How Colorado is Impacted By Nonnative Plants

Justification: 
  Colorado is home to very unique plants which serve the connected ecosystem. With birds, fish, insects, and other animals relying on these native plants, they can be threatened by nonnative species and their presence in Colorado. With the presence of these nonnative species, there are uncertain effects that can pose problems [@byrne2010impacts]. The determination of if these nonnative species in Colorado are harmful or helpful needs to be looked into and researched more. There have been studies in Rocky Mountain National Park, that state there is a uneven distribution of native and nonnative plants within RMNP, and that this biological and geological difference is a contributing factor of the relationship between these two types of plant [@kumar2006spatial]. To understand this relationship would prove to be helpful to the biodiversity of Colorado, as there are many fragile ecosystems within the state that will either be negatively or positively impacted by nonnative species. 

Research objective/question/hypothesis: 
  How does the relationship between nonnative and native plant species change throughout Colorado?

  Proposed methods: The variables I would include would be the nonnative species within Colorado, the native species, and a time span of around 25-30 years, as plants and their influence on the environments around them take a long time to show effects. I will perform a statistic test to determine their correlation based on the data that I find as well as plotting the results I get. I’ve found a datasets on data.gov about nonnative plants, and areas of critical environmental concern, both in Colorado, as the scope will be just Colorado. Again, I will be looking at the datasets to take into consideration the skewness of the data, as make changes accordingly. 

  Expected Outcomes: I expect theses outcomes to be not straight forward, like my previous proposal. Due to previous knowledge, the influence of nonnative plants on biodiversity is a very complex relationship, so I think in parts of the data there will be points of proof that there is a negative and positive correlation between the two and their interactions. 

## Section 3 Avery

#### Proposal 1: Shifts in Bird Migration Patterns Due to Changing Climate

Justification: 
As human-caused climate change continues to accelerate at concerning levels, it is essential to track the responding changes in ecosystems in order to conserve and sustain them. All organisms will be affected by these changes and will either have to adapt or face the risk of extinction. In response to climate change, one change we can expect to see across many species is, change in migration and distribution patterns. Migratory birds contribute significantly to various ecosystems, and according to [@kolevcek2020shifts], increasing temperatures leads to shifts in species abundance. Shift in abundance are extremely important to monitor from a sustainability standpoint. Ecosystems offer many services that we rely on, hence part of the importance in conserving and sustaining them. In addition, [@tomotani2018climate] reports that climate change may ultimate lead to negative changes in bird species fitness. Migratory birds also play a role in maintaining plant and vegetation growth through seed dispersal. Thus, shifts in their migratory patterns could negatively effect plant growth. 

Research objective/question/hypothesis: 
Through this study I aim to discover how bird migratory behavior is affected by climate change. My hypothesis is: changes in temperature and weather patterns are drivers of shifts in bird migration. I will use a regression model to assess the relationship between climate (independent variable) and bird migration (dependent variable).  

Proposed Methods:
I plan to use a dataset that shows climate (including variables such as temperature, precipitation, rainfall, etc) throughout many year, which I then plan to filter to the U.S. and a 10 year timeframe. I also plan to use data on bird migration patterns (this may be several dataset), that show variables such as species, geographic info, distance traveled, migration times (start, end, variability). Additionally, if needed I will narrow my spatial scope by choosing 6-12 different states to look at. Before I do any statistical testing on my data I will be testing for a normal distribution. If it is not normally distributed I will have to use different statistic tests.

Expected Outcomes:
I expect to see a relationship between change in climate and change in migration patterns, thus I expect to reject the null hypothesis. This is an important outcome to get because it will be reflective of the current threat of climate change to biodiversity and ecosystems.  

## Section 4

#### Proposal 2: Monocropping Affects on Soil

Justification:
Monocropping is a common agricultural practice where a single crop is grown for an amount of time. This agriculture practice is shown to cause diminishing effects on soil health, which accoring to [@belete2023effect] can have serious economic consequences. Monocropping increases soil infertility which decreases crop yields and soil quality. [@belete2023effect] also illustrates that monocropping causes changes in “soil microbial communities, nutrient availability, and allelopathy effect”. Additionally, often times as farmers try to combate decreasing yields by using synthetic fertilizers, which is very bad for soil health. Ultimately, monocropping is not sustainable for either the environment or the economy, thus a change is needed. Further studies are also needed to quantify monocroppings effect in order to spur change. [@katherasala2024unveiling ] empashise the importance of educating farmers of monocultures harmful effect and alternative sustainable farming methods. Furthermore, with a reduce in crop fields, food security for many communities will be put at risk. Thus, clearly understand monocroppings affects on soil health and fertily is important for safeguarding food security. 

Research objective/question/hypothesis: 
This study will aim to analyze the long-term effects of mono-cropping on soil health. For the sake of this study, soil health will be measure by soil fertility, soil diversity, and nutrient cycling. The hypothesis for this study is: Over time mono-cropping depletes soil health, fertility, and biodiversity. 

Proposed Methods:
The datasets used will include variables such as: soil pH, organic matter content, microbial diversity, and nutrient levels. Data on crop yield would also be a helpful comparisson. I will get my data maily from the USDA’s National Resources Inventory. I think both ANOVA tests or regression analysis would work for testing my hypothesis. I intend to use data from the U.S. and that was collected over a span of 10 years.

Expected Outcomes:
I expect to see that moncropping leads to a decline in soil health over time. Which will emphasize the importance for farmer to switch to more sustainable farming practices.

